### ISSUE TITLE
Is there any plans to implement something like Turbo Vision?

### ISSUE THREAD

**Issue by rgl** [gizak/termui#109]
Is there any plans to implement something along the lines of [Turbo Vision](https://en.wikipedia.org/wiki/Turbo_Vision) or [Free Vision](http://wiki.freepascal.org/Free_Vision)? That is, having windows and widgets?

You can see images about its widgets at the [google images](https://www.google.com/search?q=turbo+vision) (switch to the images tab).

PS I've also asked this question at [gocui](https://github.com/jroimartin/gocui/issues/73), but I'm not sure which project is best positioned for having this.

**Comment by gizak** [comment]
Yes it is in the roadmap, and it will be implemented in v3 at some point. The looks might not be as complex as Turbox Vision or similar, which is saying it wont has shadows or fancy fringes.
