### ISSUE TITLE
Any idea to make termui works in Web?

### ISSUE THREAD

**Issue by smcduck** [gizak/termui#120]
Web UI is widely used, and independent with terminal, you can access the UI in anytime after app started. But web page is hard to design for backend developers. If termui can be used in terminal and web, that will be wonderful.

Any solution for this?

**Comment by CuberL** [comment]
How about using [docker](https://github.com/docker/docker) and [codetainer](https://github.com/codetainerapp/codetainer)?

**Comment by promix17** [comment]
https://github.com/yudai/gotty works quite well for sharing termui via Web

**Comment by cjbassi** [comment]
+1 for gotty. Termui doesn't have any plans native web functionality atm.
