### ISSUE TITLE
Panic when List height is less than 2 (and borders are enabled)

### ISSUE THREAD

**Issue by warmans** [gizak/termui#14]
Hi, 

I've found an issue with Lists. The following code will generate a panic: 

```go
package main

import "github.com/gizak/termui"
import "github.com/nsf/termbox-go"

func main() {
	err := termui.Init()
	if err != nil {
		panic(err)
	}
	defer termui.Close()

	termui.UseTheme("helloworld")

	ls := termui.NewList()
	ls.Items = []string{"[0] github.com/gizak/termui"}
	ls.Width = 25
	ls.Height = 1

	termui.Render(ls)
	termbox.PollEvent()
}
```

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/gizak/termui.(*List).Buffer(0xc208066000, 0x0, 0x0, 0x0)
	/home/warmans/go/src/github.com/gizak/termui/list.go:82 +0x490
github.com/gizak/termui.Render(0xc20805af50, 0x1, 0x1)
	/home/warmans/go/src/github.com/gizak/termui/render.go:51 +0xc7
main.main()
	/home/warmans/go/src/github.com/gizak/termui/example/list.go:26 +0x1fc

goroutine 5 [runnable]:
os/signal.loop()
	/home/warmans/Downloads/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/home/warmans/Downloads/go/src/os/signal/signal_unix.go:27 +0x35
exit status 2
```

line 82 of list is:

```go 
trimItems = trimItems[:l.innerHeight]
```

It would seem that `l.innerHeight` is set to -1 which prevents the slice from working. I believe the reason for this is that it deducts 2 from `Height` for the top and bottom border to get `innerHeight`. As such setting the Height to 2 will avoid the error. This is fine if you understand that the borders contribute to the height but is a bit unintuitive, particularly when the heights are calculated dynamically.

The following code prevents the error but renders a blank list

```go 
if l.innerHeight < 0 {
	trimItems = make([]string, 0)
} else {
	if len(trimItems) > l.innerHeight {
		trimItems = trimItems[:l.innerHeight]
	}
}
```

**Comment by gizak** [comment]
> This is fine if you understand that the borders contribute to the height but is a bit unintuitive, particularly when the heights are calculated dynamically.

it's sure a little bit unintuitive, but if bring all the margin, border and padding terminologies may make it complex. I originally thought it would be good that let users do a little math but keep the box model simple.

Anyway, `innerHeight` may be a general problem, so I traced back and changed `align()` in `block.go`, set `innerHeight` and `innerWidth` to zero when they are negative.
