### ISSUE TITLE
Keys doesn't works

### ISSUE THREAD

**Issue by MarcusMann** [gizak/termui#140]
When trying to use keys like Q to exit for example.
The app does not respond, I have to close the terminal in hand.

Ubuntu / Linux is what I use.

**Comment by dh1tw** [comment]
are you running the unmodified example? 

Can you confirm that an event handler exists? 

```
	termui.Handle("/sys/kbd/q", func(termui.Event) {
		termui.StopLoop()
	})
```

Here the examples work as expected with Ubuntu 16.04 and 14.04.

**Comment by dongyuhappy** [comment]
I have also encountered this problem. 
MacOS is what i use

**Comment by cjbassi** [comment]
Events have been reworked so you can use the method decomented in the readme now. :+1:
