### ISSUE TITLE
support float values for barchart

### ISSUE THREAD

**Issue by AnirudhVyas** [gizak/termui#141]
I am writing a barchart terminal type cummulative app that has CPU usage times often in 0.1ish range - I want that data to be visible - is there a float data type that I can use instead of []int{} ?

Please advise ...

**Comment by AnirudhVyas** [comment]
i sent a pull request for this - please let me know if that is acceptable... https://github.com/gizak/termui/pull/142

**Comment by cjbassi** [comment]
Just added this to master with 958a28575d7411492d25e42da3ad5a6e5947d9a4 during the rewrite I did.
