### ISSUE TITLE
Cannot seem to capture mouse event.

### ISSUE THREAD

**Issue by deepakkamesh** [gizak/termui#151]
I cannot seem to capture the mouse event

termui.Handle("/sys/mouse", func(e termui.Event) {
  fmt.Println("Mouse event")
})

any thoughts?

**Comment by deepakkamesh** [comment]
Looks like it was not implemented. See accept pull request with fix.

https://github.com/gizak/termui/pull/152

**Comment by cjbassi** [comment]
Added mouse events! Check the event.go file for more info. Also check the readme/wiki for details on changes to the event system.
