### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by vsobotka** [gizak/termui#155]
Hi, I just started to learn Go and I find this project really interesting. Is there anything I can do to help? I was looking at the list #128, so I would probably try to solve something there. Or is there anything with higher priority you could use a hand with?

**Comment by cjbassi** [comment]
Hi, thanks for asking! I realize this was opened a while ago, but termui has just undergone a major rewrite and a lot of things have been cleaned up so I thought this would be a good time to get back to you. I just went ahead and tagged all the issues that I thought would be manageable for someone to work on on their own as `good first issue`, so feel free to check out any of those!
