### ISSUE TITLE
Text editing?

### ISSUE THREAD

**Issue by nickfromXXII** [gizak/termui#156]
Hello,
I want to use this package to create a client for messenger, but I haven't found any information about widgets providing text editing. Is there possibility to edit text in the widgets? If not, is this feature already planned?

**Comment by hvze** [comment]
I've sort of manipulated this by creating my own text buffer and using a wrapper struct, good luck getting text wrapping to work dynamically.

**Comment by cjbassi** [comment]
Definitely something I'd like to add. This seems like a duplicate of #34 tho so I'm going to close this.
