### ISSUE TITLE
Feature Request:GUI Builder

### ISSUE THREAD

**Issue by Immortalin** [gizak/termui#16]
Hi, do you mind doing a winforms style GUI builder for this? Golang is really lacking in decent native easy-to-use GUI libraries and termui seems to fit this niche perfectly. Thanks in advance!

**Comment by gizak** [comment]
Actually there is a newly GUI lib https://github.com/google/gxui which seems nice. Maybe we can use a config file instead of GUI builder to construct layout, more easy to implement.

**Comment by Immortalin** [comment]
I am really hoping that someone come up with a cross-platform winform type solution. In winform, GUI building is really easy as it essentially generates the call-back code for you the moment you start building the GUI so you can become productive really quickly!
