### ISSUE TITLE
handler for "/sys/kbd/<" key is activated by other keys such as space

### ISSUE THREAD

**Issue by mischief** [gizak/termui#161]
the following code will produce this message when space is pressed:

```
	termui.Handle("/sys/kbd/<", func(e termui.Event) {
		fmt.Printf("%#v\n", e)
	})
```

```
termui.Event{Type:"keyboard", Path:"/sys/kbd/<space>", From:"termbox", To:"", Data:termui.EvtKbd{KeyStr:"<space>"}, Time:1501151628}
```

this is certainly unexpected behavior.

**Comment by cklein** [comment]
This is because `isPathMatch` only compares the `len(pattern)` first bytes,
given pattern `"/sys/kbd/<space>"` and path "/sys/kbd/<", this yields true.
A naïve patch breaks the unittests, I'm not sure yet if any code relies on this behaviour.

**Comment by mischief** [comment]
yes, it does just compare the bytes. however the current implementation seems to preclude the binding of the "<" key, which is an undesirable limitation of a library like this. also using these weird `/sys` strings is silly.

**Comment by cjbassi** [comment]
Keypress handling has been reworked and this should be working now. :+1:
