### ISSUE TITLE
Feature request: "Table" widget

### ISSUE THREAD

**Issue by djhworld** [gizak/termui#17]
This is really cool, but do you know what would make it cooler? A table widget!  Maybe something like https://github.com/olekukonko/tablewriter

**Comment by warmans** [comment]
+1

**Comment by gizak** [comment]
Seems pretty nice, I will keep that in mind!

**Comment by jingweno** [comment]
:+1:

**Comment by pyros2097** [comment]
![screenshots](https://cloud.githubusercontent.com/assets/1687946/12205047/40c5484c-b65e-11e5-9843-fdd2b39952f2.png)

Well I'm working on a download manager and have created something like a table.
