### ISSUE TITLE
Printing output without loop for non-interactive contexts

### ISSUE THREAD

**Issue by ljfranklin** [gizak/termui#175]
Hi all,

I'm looking to build a CLI for use in a CI pipeline. Is there a way to have `termui` print its output to the screen without a loop and not clear the output on exit? I'm new to fancy terminal UI apps so apologies if I'm missing something obvious.

**Comment by ljfranklin** [comment]
To rephrase, is it possible for `termui` to operate in non-full screen mode?

**Comment by cjbassi** [comment]
Hmm, unfortunately I don't think so. I'm actually not too familiar with the underlying mechanics of terminal drawing in general, but at least with termbox-go, I don't think it's possible.
