### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by practice** [gizak/termui#177]
```
$ go get -u github.com/gizak/termui
# github.com/gizak/termui
../../../github.com/gizak/termui/render.go:107:30: not enough arguments in call to stack.ParseDump
        have (*bytes.Reader, *os.File)
        want (io.Reader, io.Writer, bool)
../../../github.com/gizak/termui/render.go:112:10: undefined: stack.Palette
../../../github.com/gizak/termui/render.go:113:15: undefined: stack.SortBuckets
../../../github.com/gizak/termui/render.go:113:33: undefined: stack.Bucketize
../../../github.com/gizak/termui/render.go:114:22: undefined: stack.CalcLengths
```

maruel/panicparse API has changed 3 days ago.

**Comment by jinyeom** [comment]
Having the same problem!

**Comment by robertely** [comment]
I'm seeing this on Travis builds as well. This Repo appears abandoned but @gizak is there any way you can come back to vendor some dependencies ?

**Comment by svenfinke** [comment]
Yeah... the last commit was on Jan 2. Damn.... I guess I'll fork this in the afternoon and check if I can fix this :D

**Comment by raydac** [comment]
also detected the error in my set of examples for maven golang plugin, the incompatibility for new  version of https://github.com/maruel/panicparse , termui is compatible with tag v1.0.2 so that if to use library 1.0.2 then build works well

**Comment by airking05** [comment]
If you want to use fixed ver, use this master branch https://github.com/airking05/termui.

**Comment by cjbassi** [comment]
Just changed some dependency management things and I'm not getting this issue anymore. Could someone confirm it's working for them too?

**Comment by cjbassi** [comment]
Great, closing this then.
