### ISSUE TITLE
Package is not able to install because of refactorings in https://github.com/maruel/panicparse

### ISSUE THREAD

**Issue by unterstein** [gizak/termui#179]
This package fails to install with this error message:

```
junterstein$ go get github.com/gizak/termui
# github.com/gizak/termui
Go/src/github.com/gizak/termui/render.go:107:30: not enough arguments in call to stack.ParseDump
	have (*bytes.Reader, *os.File)
	want (io.Reader, io.Writer, bool)
Go/src/github.com/gizak/termui/render.go:112:10: undefined: stack.Palette
Go/src/github.com/gizak/termui/render.go:113:15: undefined: stack.SortBuckets
Go/src/github.com/gizak/termui/render.go:113:33: undefined: stack.Bucketize
Go/src/github.com/gizak/termui/render.go:114:22: undefined: stack.CalcLengths
```

This is because this project made a refactoring and moved `Palette` from `stack` to `internal`, see this commit: https://github.com/maruel/panicparse/commit/822a960846af9ee106aaff0da10f587cbb317e35

**Comment by zuston** [comment]
yep, i meet the same problem. 
thanks your solution

**Comment by zuston** [comment]
i think you should fork the project and refix bug by pulling request

**Comment by unterstein** [comment]
I'm not familiar with go, but would it be possible to change the usage of this struct within this project from `stack` to `internal` or is `internal` a magic package that can not be used outside the other go project?

**Comment by airking05** [comment]
Hi,
this issue is duplicated.
Check #177

**Comment by unterstein** [comment]
Thank you @airking05 for referencing this issue and sorry for not seeing it :(
