### ISSUE TITLE
Line chart renders incorrectly if initialized with empty dataset

### ISSUE THREAD

**Issue by warmans** [gizak/termui#18]
If a line chart starts with no values and values are added later the points are drawn into the title line. 

For example:

```
	writeLatency := ui.NewLineChart()
	writeLatency.Border.Label = "Write Latency"
	writeLatency.Data = []float64{} //no values
	writeLatency.Height = 10
	writeLatency.AxesColor = ui.ColorWhite
	writeLatency.LineColor = ui.ColorGreen

        //now start updating 
```

**Comment by gizak** [comment]
Guess caused by initializing axes without actual data points, will look into it soon!

**Comment by gizak** [comment]
You didn't set `writeLatency.Width = ??` in the first place. However If you did set it but it's not enough large, it   would still draw incorrectly (override setting width). WIP.
