### ISSUE TITLE
Co-maintainer needed

### ISSUE THREAD

**Issue by gizak** [gizak/termui#188]
In response to https://github.com/gizak/termui/issues/164 https://github.com/gizak/termui/issues/128 and many contributors and lib users.

Since I could not work on this project on regular hours and maintaining & developing is lagging behind, can someone help with this as a project maintainer? 

The job requires Go and terminal experiences.  Works will include managing pull requests, hotfixes, completing doc/references and other general improvements. 

If you are willing to take on this job please leave a message on this thread or contact me by email. Thanks for your contributing!

**Comment by cnbuff410** [comment]
Is this in progress?

**Comment by cjbassi** [comment]
I'd be open to co-maintaining. I actually created my own fork of this repo [here](https://github.com/cjbassi/termui) for [gotop](https://github.com/cjbassi/gotop) which ended up being almost a complete rewrite so I'm quite familiar with the codebase. I could also add back some of the improvements I made too.

**Comment by gizak** [comment]
@cjbassi Checked the repo and the improvements you made are great 👍! Thank you very much for taking this job and glad to have you on board! I will add you to Collaborators.
