### ISSUE TITLE
sparklines and line chart from example/theme.go don't look right on raspberry pi (should they?)

### ISSUE THREAD

**Issue by hagna** [gizak/termui#19]
Using raspbian wheezy (2015-02-16).  Cross compiled example/theme.go and ran it on the console of the pi.

Maybe the pi is missing a font?

**Comment by gizak** [comment]
I do not have an experience with raspberry pi, but I guess the problem may be the unicode displaying. The sparklines and line chart rely upon unicode, so make sure your terminal and font's settings are correct.

**Comment by hagna** [comment]
Ok well it looks like there are ~24 characters that I don't have: the brail ones and the blocks.
