### ISSUE TITLE
Rework event system - b227bd5 - deprecated '/sys/kbd/' catchall keys

### ISSUE THREAD

**Issue by jalder** [gizak/termui#190]
Is there a new equivalent for catch all keyboard input Handle() events?  Documentation shows this as previously being "/sys/kbd", unable to find a working equivalent since the update.

If it's better to have another event capture method for this type of work, let me know.

**Comment by cjbassi** [comment]
Just readded this with the `<Keyboard>` keyword. And also added `<Mouse>` to handle all mouse events.

**Comment by jalder** [comment]
Holy smokes! Thanks for the quick resolution.
