### ISSUE TITLE
Question on line charts

### ISSUE THREAD

**Issue by ChrisPikul510** [gizak/termui#192]
I didn't see things direct to this question in the readme or otherwise. This is NOT an issue per say. To the point. How would I go about (and can I) for doing double layered graphs. As in. A average layered over a real-time type situation. I'm considering using this as a terminal based analytics for actual break-neck live info, and I collect avg, over current in a time period and would like to have this information displayable via a library like this. So yeah, layering of data is it possible?

**Comment by cjbassi** [comment]
You can have multiple data sources in a linechart, so basically you can have 2 lines in one chart. Is that what you mean?

**Comment by ChrisPikul510** [comment]
Oh yup. Found it! Thanks
