### ISSUE TITLE
Run under Tmux ??

### ISSUE THREAD

**Issue by andyl** [gizak/termui#20]
On Ubuntu 14.04 - everything looks great in Terminator (xterm).

But - from Tmux 1.9a the screen looks bad.  Anyone have any luck running termui under Tmux??

**Comment by Matt3o12** [comment]
Could you send us a screenshot of your bad screen (just attach it to this issue)?

Please make sure that your Term variable is set correctly in Tmux:

    export | grep TERM

should return `TERM="xterm-256color"`. If it doesn't please try setting it manually:

    export TERM="xterm-256color"

**Comment by andyl** [comment]
Screenshot attached - I tried 'xterm-256color', 'xterm' and 'screen-256color' (the default).

![termui](https://cloud.githubusercontent.com/assets/90030/6943386/888ab6f8-d842-11e4-9c77-c76da778ea0b.png)

**Comment by gizak** [comment]
Probably because you set Unicode East Asian Ambiguous characters are wide, so some unicode chars width are messed up. Not sure how to correct it for Tmux :(

**Comment by andyl** [comment]
FYI my terminal software (Terminator) doesn't have a 'Unicode East Asian Ambiguous' character option.  My default encoding for Terminator is `Unicode UTF-8`.

Also FYI I tried using other terminal programs (`xterm` and `xfce4-terminal`) w/o success.

**Comment by jesseward** [comment]
@andyl for what it is worth, this is rendering ok under my Tmux instance 

![tmux-termui](http://i.imgur.com/AMkG0PW.png)

some relevant settings from my environment
```
LANG=en_US.utf8
COLORTERM=gnome-terminal
TERM=screen-256color
tmux-1.6-3.el6.x86_64 (RHEL 6.4)
```
my .tmux.conf -> http://pastebin.com/5gxVhzFA . Tmux runs under gnome-terminal, which is served by the i3 wm.

**Comment by andyl** [comment]
Thanks for the info.  Tried to copy your settings with no luck.  I am running Tmux Version 1.9a using the Terminator console.  Also tried with gnome-terminal didn't work.

**Comment by andyl** [comment]
OK it works for me now.  The fix was a tmux configuration - in `~/.tmux.conf`:

    set -g utf8
    set-window-option -g utf8 on
    set-option -g default-terminal "screen-256color"
