### ISSUE TITLE
undefined `isPathMatch` and `NewPar`

### ISSUE THREAD

**Issue by utkarsh2102** [gizak/termui#204]
After patching `termui.PollEvent`, here's another build failure while building this package:

```
src/github.com/gizak/termui/events_test.go:22:11: undefined: isPathMatch
src/github.com/gizak/termui/paragraph_test.go:10:9: undefined: NewPar
FAIL	github.com/gizak/termui [build failed]
?   	github.com/gizak/termui/test	[no test files]
dh_auto_test: cd obj-x86_64-linux-gnu && go test -vet=off -v -p 2 github.com/gizak/termui github.com/gizak/termui/test returned exit code 2
```

**Comment by cjbassi** [comment]
Yah the test files are pretty outdated. Currently working on some major changes so those are on the backlog for now.

**Comment by cjbassi** [comment]
No idea :D I'll let you know when it's merged tho.

I'm curious about the Debian packaging. You're saying you'll package this library for the Debian repos?

**Comment by utkarsh2102** [comment]
Haha, yes! :D
I can package this for all the Debian repos.
So `apt install termui` would be a way to install on all Debian systems ;)

**Comment by cjbassi** [comment]
Just removed all the test files so this should be fixed now :D Hopefully going to add them back soon, but I just did a major rewrite so they were pretty unusable.
