### ISSUE TITLE
Make termui Go modules friendly

### ISSUE THREAD

**Issue by divan** [gizak/termui#225]
As termui is a project that's actively being developed through years and sometimes breaks API, It would be awesome to make it friendly to the Go modules.

A couple of specific things here:
1. Tag new versions before any API breaks. It'll give some cushion and enough time to transition to the new API, and the transition will be as easy as bumping up the version in go.mod. Latest "The Great Rewrite" commit definitely deserved new version, for example.
2. Currently, go mod marks `termui` as `+incompatible` because of v2 version. You will probably need to change module definition in go.mod to `module github.com/gizak/termui/v2` to play nice with Go modules.

Thanks for the terrific library!

**Comment by cjbassi** [comment]
Thanks for the suggestions. So I'm pretty confused about this whole go modules business tbh. I checked out the go modules wiki and it sounds like:

1. I need to create a new `v3` release to properly add go module support.
2. I need to update the module definition in `go.mod` to include `v3`.
3. Packages that use termui need to include `v3` in the import path.

How would that compare to updating the current `go.mod` file to include `v2` in the module definition?

Also, termui is still in the process of figuring out the API, so more breaking changes may still be in the works fwiw.

**Comment by cjbassi** [comment]
Also, what's the issue with installing termui using the recommended method of doing
```go get -u github.com/gizak/termui@master``` for the time being? Genuinely curious, especially since termui is still in flux atm.

**Comment by sedlund** [comment]
I am very new to this as well, and am getting the +incompatible flag and the old tag doesn't seem to compile for me.

I think adding a 2.3.1 tag would fix it.

**Comment by cjbassi** [comment]
So v3 was just released with Go module support! You'll have to update your import paths to include `v3` as per Go modules convention for modules >v1. There was also a few minor breaking changes just to clean up the API, but those are all done now :relieved: . Also, I don't think backporting Go modules to v2 is really worth it. So at this point, I think this issue is resolved. I'm closing this but let me know if there's any issues with Go modules or migrating to v3.
