### ISSUE TITLE
Two lists in two rows in one column in grid: Second list does not scroll

### ISSUE THREAD

**Issue by snipem** [gizak/termui#228]
See my example, the second list down below does not scroll to the other entries when reaching the last entry.

When both lists are in two columns next to each other the bug does not appear.

In the demo the first list can be controlled with up and down and the second with j and k.

https://gist.github.com/snipem/6558cee902d131ffe87ad4c1a60d9a39

**Comment by cjbassi** [comment]
Thanks for pointing that out. Should be fixed now but let me know if you still get issues.

**Comment by snipem** [comment]
Looks great now. My production code is working. Thank you very much.
