### ISSUE TITLE
termbox-go copyright notice on events.go

### ISSUE THREAD

**Issue by beefsack** [gizak/termui#25]
Noticed [events.go](https://github.com/gizak/termui/blob/7be8d021fddd4edda61672d8ebfe0acda4d3d72b/events.go) uses source from [termbox-go](https://github.com/nsf/termbox-go/blob/54b74d087b7c397c402d0e3b66d2ccb6eaf5c2b4/api_common.go), you might want to make sure their [license](https://github.com/nsf/termbox-go/blob/master/LICENSE) appears somewhere relevant.  Perhaps appending their license to your own LICENSE file and preceding it with something like "Portions of this library uses source from termbox-go under the following license".

**Comment by gizak** [comment]
Thanks for pointing out! These two licenses are essentially the same. I added a link pointing to the termbox-go's authors file and the license file.

**Comment by beefsack** [comment]
Yeah that's right, they're both MIT, I think the most important part is that copyright line at the top if the licenses match.
