### ISSUE TITLE
Keybindings not working on FreeBSD

### ISSUE THREAD

**Issue by miguelmota** [gizak/termui#254]
I run the demos but can't quit using any of the keybindings. I tested it on a fresh install of FreeBSD. Examples work fine on linux though. Any idea?

**Comment by miguelmota** [comment]
Resolved https://github.com/nsf/termbox-go/pull/219/files

**Comment by xxxserxxx** [comment]
@miguelmota Any chance of another release that includes this fix?  Maybe a patch release, v3.1.1?

**Comment by miguelmota** [comment]
@xxxserxxx I recommend forking it and using your own patched version considering there's little dev activity in the project
