### ISSUE TITLE
GridLayout doesn't render the borders consistently

### ISSUE THREAD

**Issue by Matt3o12** [gizak/termui#26]
When using the GridLayout with different spans (that add up to 12), the border is not rendered consistently (i.e. the width of the first row is longer/short then the width of the second one). 

Here is an example:  
![screen shot 2015-04-09 at 10 45 22 pm](https://cloud.githubusercontent.com/assets/1218474/7076825/6cd435ee-df0c-11e4-9e61-58bd48b7886b.png)  
[Here is the example code.](https://gist.github.com/509957fda48f2e4e677d).

When I set an `offset` of `1` (the second parameter of `NewCol()`), that seems fix it but I'm not quite sure whether it's a bug or a feature. The docs don't mention the `offset`, either (maybe you could at least explain what `offset` does)...

**Comment by gizak** [comment]
It definitely not a feature... and hey you've found a new bug about `offset`;)

The `.Offset` works like a placeholder, if the first col in a row has span 3 and offset 7, the col's `X` will be `row's X + 7/12 * row's Width`. e.g.:
![20150409174521](https://cloud.githubusercontent.com/assets/2100512/7077616/4f54d612-dee0-11e4-9ff5-db5dc1b059b3.png)

Slightly changed your test code:
```go
package main

import ui "github.com/gizak/termui"

func main() {
	err := ui.Init()
	if err != nil {
		panic(err)
	}

	defer ui.Close()
	ui.UseTheme("helloworld")

	foo := ui.NewPar("Foo")
	foo.Height = 20

	bar := ui.NewPar("BAR")
	bar.Height = 20

	all := ui.NewPar("aLLLL")
	all.Height = 10

	ui.Body.AddRows(
		ui.NewRow(
			ui.NewCol(3, 7, foo),
			ui.NewCol(2, 0, bar),
		), ui.NewRow(
			ui.NewCol(12, 0, all),
		),
	)

	ui.Body.Align()
	ui.Render(foo, bar, all)

	<-ui.EventCh()
}
```

And for the border issue, my guess is there may be some minor bugs regarding converting float to int. Will look into it soon.

**Comment by Matt3o12** [comment]
Oh, now I get it (you should mention it in the docs, though).
But the +1 offset workaround doesn't always seem to work, though. It only does when the terminal with is an even number :)

**Comment by NHOrus** [comment]
I want to reopen this issue:

it still happens, on odd terminal sizes.

this is 150x39 in xterm
![border_problemless](https://cloud.githubusercontent.com/assets/5390835/7225215/cdbb620c-e744-11e4-824a-560c408080ce.png)
this is 149x39 in xterm
![border_problem](https://cloud.githubusercontent.com/assets/5390835/7225214/cdb95ea8-e744-11e4-841d-14a4ffe8c897.png)

Border misaligment is painfully visible, still.
