### ISSUE TITLE
is x axis using assuming input array index is input value?

### ISSUE THREAD

**Issue by fxfactorial** [gizak/termui#279]
Great lib - 

So I want to make a plot like 

![](http://parasec.net/transmission/order-book-visualisation/images/order-book-liquidity.png)

and you'll see that the x axis is not starting at 0 

from what i see in these examples and what i tried, the x axis is the index of the array. I want to do the braille style and i have this so far 
![Screenshot from 2020-09-28 13-53-39](https://user-images.githubusercontent.com/3036816/94468185-e420f300-0178-11eb-82b4-f72baeb7ba35.png)

but the x axis still wrong, starting from 0 . Can you show an example somewhat approximating the initial graph i showed?

EDIT: and it was referenced here too: 
https://github.com/gizak/termui/pull/78#issuecomment-636241432

so I tried all the examples in plot.go and none are able to have the x axis not start from 0 -

**Comment by fxfactorial** [comment]
so it seems there is no way to not have a 0 origin

```
	buf.SetString(
		"0",
		NewStyle(ColorWhite),
		image.Pt(self.Inner.Min.X+yAxisLabelsWidth, self.Inner.Max.Y-1),
	)
```

**Comment by chromafunk** [comment]
Is this going to be ever fixed ? Or is this project dead ? I'm having the same issue and I have invested quite a bit of time setting up this

**Comment by fxfactorial** [comment]
I moved on - project seems dead

**Comment by chromafunk** [comment]
what did you ended up using ? thanks

**Comment by fxfactorial** [comment]
Nothing - just moved on =/
