### ISSUE TITLE
undefined: termui.EventCh, termui.EventKey

### ISSUE THREAD

**Issue by charliedrage** [gizak/termui#36]
A bit new to Go. I've imported the library, then I've ran go run against the grid.go example, but I'm getting undefined errors.

Have the examples not been updated lately or is this a noob mistake?

```bash
❯ go get github.com/gizak/termui
                                                                                                                                                                                             
~/test   
❯ go run grid.go 
# command-line-arguments
./grid.go:101: undefined: termui.EventCh
./grid.go:107: undefined: termui.EventKey
```

Thanks for being patient with me!

**Comment by gizak** [comment]
It seems weird, but I think you can try `go get -u github.com/gizak/termui` to update the package and try the test cases again.

**Comment by charliedrage** [comment]
@gizak 
You're right, that was it. Y U DO THIS GO.

Thanks a lot!
