### ISSUE TITLE
Add possibility to add Rows/Cols dynamically to the Grid.

### ISSUE THREAD

**Issue by divan** [gizak/termui#42]
The Grid layout idea is amazing, but here is the situation that cannot be solved with current design: adding arbitrary number of Rows/Cols, calculating it's number dynamically.

I can do:

    col1 := termui.NewCol()
    col2 := termui.NewCol()
    termui.NewRow(col1, col2)

but if I need to create 4 or 10 cols, depending on some state, I cannot create slice of termui.*row, because it's unexported.

So, here are two most obvious solutions:
  - make row type exported
  - add new functions for that, like AddCol()

Maybe there is another way to accomplish that? Or should we wait until refactoring branch will be merged and it will have Grid redesigned?

**Comment by gizak** [comment]
I think making row exported is an easy fix, and this has been done in refactoring. I will push a hotfix to master soon. At this moment I do not think Grid will change a lot, so there might be some minor changes but nothing more.
