### ISSUE TITLE
ui.TermWidth() returns incorrect value if ui.Render() has not being called first

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [gizak/termui#43]
I was updating grid.go so that it didn't use 100% CPU, and I ran across this bug.

```
	go func() {
		for _ = range time.Tick(time.Second * 4) {
			update <- true
		}
	}()
	ui.Render(ui.Body)
	for {
		select {
		case e := <-evt:
			if e.Type == ui.EventKey && e.Ch == 'q' {
				return
			}
			if e.Type == ui.EventResize {
				ui.Body.Width = ui.TermWidth()
				ui.Body.Align()
				ui.Render(ui.Body)
			}
		case <-done:
			return
		case <-update:
			ui.Render(ui.Body)
		}
	}
```

here's the updated redraw code and you can pretty much immediately see the problem if you try this.

However, if you write it like this:

```
	for {
		select {
		case e := <-evt:
			if e.Type == ui.EventKey && e.Ch == 'q' {
				return
			}
			if e.Type == ui.EventResize {
				ui.Render(ui.Body)
				ui.Body.Width = ui.TermWidth()
				ui.Body.Align()
				ui.Render(ui.Body)
			}
		case <-done:
			return
		case <-update:
			ui.Render(ui.Body)
		}
	}
```

then it works fine. I expect ui.TermWidth() to return the current terminals width. Not the width of the terminal when ui.Render() last ran, so this was very confusing!

**Comment by gizak** [comment]
Weird... `ui.TermWidth` should return current width value. Looking into that...

**Comment by Ghoughpteighbteau** [comment]
It might actually be a bug with my terminal emulator incorrectly reporting its size? I should of considered that, I'll re-run the test on other emulators

**Comment by gizak** [comment]
It happens in my terminal too, resize always lags one step behind.

The `Render` should not be called parallel, so I used this instead:
```go
if e.Type == ui.EventResize {
	ui.Body.Width = ui.TermWidth()
	ui.Body.Align()
	go func() { update <- true }()
}
``` 

While this did not solve the problem. Now I am checking `termbox` to see if there is anything I missed.
