### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by AmandaCameron** [gizak/termui#54]
The ability to use 256-colour support in terminals that support it. I can do a fork and make a PR for this if you'd like.

I'm thinking of doing it with something like an Attribute that you | with the 0-256 value or so?

So you'd have:

``` go
  Point{
    Ch: ' ',
    Bg: termui.Attr256Colour | 12,
  }
```

**Comment by gizak** [comment]
Or something like `Bg: termui.AttrBlack | 12` which gives a "8-color compatible" option? PRs are always welcome :)
