### ISSUE TITLE
Does not support Windows?

### ISSUE THREAD

**Issue by wclssdn** [gizak/termui#55]
rt...

**Comment by klauern** [comment]
I haven't seen that on my system (Win7).  Is there a demo that isn't working or an example that you could have me try to see if I can reproduce it?  I'm not a dev on this project, but I was thinking of using this for some apps that I wanted to write.

**Comment by wclssdn** [comment]
it does not work on my system(windows 7)...

**Comment by klauern** [comment]
Hm.  Are you using `cmd.exe` or `PowerShell`?

Powershell:
![PowerShell](http://i.imgur.com/GKjlNUE.png)

cmd.exe
![PowerShell](http://i.imgur.com/2biKDyE.png)

**Comment by wclssdn** [comment]
Strange,it works now...
