### ISSUE TITLE
API stabilization/versioning

### ISSUE THREAD

**Issue by NHOrus** [gizak/termui#56]
With incoming refactoring there appears to be API-breaking changes.

I propose using something like gopkg.in of gopkgs.com to pin down current API as v1, and then go on with breaking changes as v2.

**Comment by omeid** [comment]
+1
I want to use termui, but I don't want it to break overnight. It would be nice if I could already use the "refactored" work.

**Comment by gizak** [comment]
Sure it's definitely needed . Any idea on which solution is better?

**Comment by NHOrus** [comment]
Sadly,  no. Most often seen gopkg.in, but not sure.

**Comment by yesnault** [comment]
Yes, gopkg.in is exactly made for that. Just tag current master as v1, that's all. See http://labix.org/gopkg.in
