### ISSUE TITLE
Handle timers

### ISSUE THREAD

**Issue by divan** [gizak/termui#58]
Hi,

how is handling timers supposed to work with new API?

Initially I thought, `Handle("/timer/Ns")` or `Handle("/timer/200ms")` should work, but it works only with `1s` timer and it seems to be hardcoded or am I missing something?

**Comment by gizak** [comment]
The 1s timer is just pre-installed in the package initializing phase along with other event channels, nothing special here:
```go
// render.go
// ....
DefaultEvtStream.Init()
DefaultEvtStream.Merge("termbox", NewSysEvtCh())
DefaultEvtStream.Merge("timer", NewTimerCh(time.Second))
DefaultEvtStream.Merge("custom", usrEvtCh)
// ....
``` 
For example, to register a 500ms timer:
```go
termui.Merge("timer", NewTimerCh(time.Second/2))
```
The new vision is lack of documents, but I am working on it.

**Comment by NHOrus** [comment]
Okay, I got no idea how it should work, I only know that attempt to rewrite my app with v2 doesn't work and leaves me baffled.

Also, maybe rename Merge to RegisterEvent?

**Comment by NHOrus** [comment]
Honestly, I also really want handle example for os.Signal

**Comment by NHOrus** [comment]
... It's amazing how wrong you are here.

Somewhy, no matter how you name your time channel, it gets named "/timer/duration" where duration is the stuff you passed to NewTimerCh.

So, if I do `ui.Merge("timer/update", ui.NewTimerCh(ptick))`
only `ui.Handle("/timer/"+ptick.String(), func(ui.Event) {})` works. WHY???

**Comment by coderant** [comment]
do
```
ui.Merge("CustomeTimer", ui.NewTimerCh(time.Millisecond * 100))
ui.Handle("/CustomeTimer", func(e ui.Event) {
		t := e.Data.(ui.EvtTimer)
		i := t.Count
		logger.Println("aaaa" + string(i))

		ui.Render(ui.Body)
	})
```

**Comment by mrkaspa** [comment]
@coderant that doesn't work

**Comment by mrkaspa** [comment]
```go
ui.Merge("/timer/2s", ui.NewTimerCh(time.Second*2))

ui.Handle("/timer/2s", func(e ui.Event) {
		t := e.Data.(ui.EvtTimer)
		i := int(t.Count)
		list.Items = strs[i%9:]
		ui.Render(p, list, g, sp, lc, bc, lc1, p1)
})
```

The ui.NewTimerCh(time.Second*2) generates the event in the format /timer/{ the time sent to NewTimerCh function}
