### ISSUE TITLE
Get Current Theme

### ISSUE THREAD

**Issue by Matt3o12** [gizak/termui#6]
Is there any reason why the variable for getting the [current theme](https://github.com/gizak/termui/blob/master/theme.go#L52) is not exported? 

This makes creating custom widgets impossible...

**Comment by gizak** [comment]
Hi @Matt3o12, thanks for pointing out! Haven't noticed this until now, I will fix it soon!

**Comment by Matt3o12** [comment]
Mind if I write a pull request?
