### ISSUE TITLE
Flickering render

### ISSUE THREAD

**Issue by byrnedo** [gizak/termui#61]
I just upgraded my project (https://github.com/byrnedo/dockdash/tree/feature/new_termui) to the latest termui. Maybe not according to best practices but just to make an easy first port I've done the following:

I have one main select loop where I hold state ( up/down position, displayable data... )
All my key handlers are signalling to a channel which is read by this select.
Any data updates are also sent to a channel which is read by the select as well.
Any of these events will trigger a render. 
I also have a timer (1s) running which signals another channel also read by this select which renders.

The basic rendering flow I have is the same as before I upgraded  ( ie all rendering is done in the same select ).

I'm experiencing flickering now though with every render. 

Is there a likely cause of this? I see that the rendering in termui is now done in a routine ( perhaps it was before too?)

EDIT: 

I notice it gets worse the larger the size  of the terminal window.

**Comment by gizak** [comment]
Hi @byrnedo I am looking into it. btw, did you have this problem with the old version of `termui`?

**Comment by byrnedo** [comment]
Hi @gizak, no it wasnt there in the old version.
Den 3 nov 2015 01:26 skrev "Zack Guo" <notifications@github.com>:

**Comment by mrezai** [comment]
Hi, in ubuntu 14.04 even examples in master branch have this problem(dashboard, grid) but there isn't in v1. There is another issue that may be somehow related to this; resizing terminal window by mouse too fast sometimes cause program closed in v2.

**Comment by byrnedo** [comment]
Hi @mrezai , Yeah I noticed the resize issue as well. I'm on 15.10 so same thing going on there.

**Comment by NHOrus** [comment]
Same with me, and bigger the size of termui window, more noticeable and pronounced flicker is.

Sometimes it's mostly black screen with periodically flashing UI.

**Comment by gizak** [comment]
Hi help me reproduce the errors. What's your OS and terminal application? I am using os x 10.11 and archlinux with gnome but none of them seems have the problem.

**Comment by mrezai** [comment]
Hi, I can see the errors in both ubuntu 14.04 desktop and server. I think the simplest way to reproduce errors is using vagrant. Install latest virutalbox and its extension pack, vagrant and finally in command line :

vagrant init ubuntu/trusty64; vagrant up --provider virtualbox

**Comment by byrnedo** [comment]
Yeah, like @mrezai I'm on ubuntu, in my case 15.05 and 15.10. 
Terminal I'm using is the built in ubuntu terminal.

**Comment by vrecan** [comment]
I'm having this problem as well on centos 7.

**Comment by vrecan** [comment]
this also happens on my mac osx 10.10. 

In both instances if I just run the grid demo it flickers if I resize the window to be larger. If I keep it small ie below 640x480 it does not flicker.
