### ISSUE TITLE
g.Block.Border.Label undefined (type bool has no field or method Label)

### ISSUE THREAD

**Issue by bwmarrin** [gizak/termui#62]
I'm new to golang and I suspect I'm just doing it wrong.  

I installed the termui library following the instructions here and created a simple test program termui.go which is a copy/paste of the "simplest example" shown here https://godoc.org/github.com/gizak/termui

When I try to run the code I get the following error.

```
go run termui.go
# command-line-arguments
./termui.go:14: g.Block.Border.Label undefined (type bool has no field or method Label)
```

**Comment by gizak** [comment]
Hi @bwmarrin , you did nothing wrong, it's just because some docs are outdated. Change the line with:
```go
g.Block.BorderLabel
```
will fix this.

**Comment by siacn** [comment]
Awesome, I'll try that and report back.

**Comment by s7v7nislands** [comment]
new to using this package, can you update the doc.go? thank!

**Comment by s7v7nislands** [comment]
@gizak the examples in the _example dir works!
