### ISSUE TITLE
Panic on resize.

### ISSUE THREAD

**Issue by NHOrus** [gizak/termui#63]
In any terminal, if I try to resize, termui.v2 app panics with:

    panic: bytes.Buffer: truncation out of range

    goroutine 416 [running]:
    bytes.(*Buffer).Truncate(0x69ac60, 0x0)
        /usr/lib/go/src/bytes/buffer.go:69 +0xbf
    bytes.(*Buffer).WriteTo(0x69ac60, 0x7fd1fb362510, 0xc8200320c0, 0xae8, 0x0, 0x0)
        /usr/lib/go/src/bytes/buffer.go:222 +0x1af
    io.copyBuffer(0x7fd1fb362510, 0xc8200320c0, 0x7fd1fb362538, 0x69ac60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:371 +0xd0
    io.Copy(0x7fd1fb362510, 0xc8200320c0, 0x7fd1fb362538, 0x69ac60, 0xc820101da8, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:351 +0x64
    github.com/nsf/termbox-go.flush(0x0, 0x0)
        /home/nho/golang/src/github.com/nsf/termbox-go/termbox.go:234 +0x96
    github.com/nsf/termbox-go.Flush(0x0, 0x0)
        /home/nho/golang/src/github.com/nsf/termbox-go/api.go:200 +0x224
    github.com/nsf/termbox-go.Sync(0x0, 0x0)
        /home/nho/golang/src/github.com/nsf/termbox-go/api.go:458 +0x61
    gopkg.in/gizak/termui%2ev2.TermWidth(0x0)
        /home/nho/golang/src/gopkg.in/gizak/termui.v2/render.go:65 +0x18
    main.main.func6(0x5b64c0, 0x6, 0x5b7ba0, 0xf, 0x5b6238, 0x7, 0x0, 0x0, 0x57f780, 0xc8201211b0, ...)
        /home/nho/workshop/tgotop/draw.go:102 +0x1c
    gopkg.in/gizak/termui%2ev2.(*EvtStream).Loop.func1(0xc8200183c0, 0x5b64c0, 0x6, 0x5b7ba0, 0xf, 0x5b6238, 0x7, 0x0, 0x0, 0x57f780, ...)
        /home/nho/golang/src/gopkg.in/gizak/termui.v2/events.go:254 +0x109
    created by gopkg.in/gizak/termui%2ev2.(*EvtStream).Loop
        /home/nho/golang/src/gopkg.in/gizak/termui.v2/events.go:256 +0x121

Function around line 102:  

    ui.Handle("/sys/wnd/resize", func(ui.Event) {
		if ui.TermWidth() > 20 {
			ui.Body.Width = ui.TermWidth()
			ui.Body.Align()
		}
		ui.Render(ui.Body)
	})

Happens in mate-terminal and terminology

**Comment by gizak** [comment]
I located the problem. the program will crash when calling `TermWidth` and `Render` at the same time. I'm working on it.

**Comment by mhoc** [comment]
I can confirm the bug with with `Render` and `TermHeight` as well.

**Comment by manipuladordedados** [comment]
Same bug here.
