### ISSUE TITLE
example ttop: not building, leaking goroutines

### ISSUE THREAD

**Issue by NHOrus** [gizak/termui#64]
a302a528a807232d794aabb0479ab14a6ac601a8/_example/ttop.go#L351 - each time first case happens, another one of time.After channels gets permanently blocked.
Also, uses `extra` instead of `_extra` for import and in general v1 api.

**Comment by gizak** [comment]
Hi, the reason of using `_extra` is because it is not fully ready, so it will change to `extra` when everything is done.
