### ISSUE TITLE
Feature request : ability to plot multiple datapoints in linechart

### ISSUE THREAD

**Issue by jesseward** [gizak/termui#79]
In the [blessed-contrib](https://github.com/yaronn/blessed-contrib) nodejs package, the linechart is able to plot multiple datapoints on a single line graph .See Vusers, Hits Per Second and Transactions Response Time in the image below. Any possibility of adding this functionality to termui ?  ![blessed-contrib](https://raw.githubusercontent.com/yaronn/blessed-contrib/master/docs/images/truload.png) .

**Comment by missingdays** [comment]
So data would be 2d array now instead of 1d.
This would totally break current API,  so I guess it would be great feature for V3.
This doesn't seem to hard to implement though.

**Comment by mranney** [comment]
I would also like to use linecharts with multiple series. Is there an implementation underway? If not, I'd be willing to contribute one.

**Comment by mranney** [comment]
I went ahead and worked up an implementation of multi-series line charts. You can see the code here:

https://github.com/uber-common/termui/tree/mjr-multi-series

It's obviously a breaking change with the existing API, but it's been very useful to me so far. Maybe we could make a new widget type of multiLineChart or something like that?

There are some issues with this when the lines intersect in a cell that I haven't addressed. I sort the series names so at least they are consistently obscured.

@gizak what do you think about this approach?

Here's a screenshot of the tool I've been working on that shows multiple graphs of multiple series. It's already being useful.

<img width="1428" alt="mjr_ubuntu____golang_src_github_com_gizak_termui_ _ssh_ _237x58" src="https://cloud.githubusercontent.com/assets/210141/12803472/39cb36f0-ca9f-11e5-9644-611dd7c1e454.png">

**Comment by cjbassi** [comment]
This has been added! Although I forget when :D
