### ISSUE TITLE
screen / byobu encoding

### ISSUE THREAD

**Issue by jonatas** [gizak/termui#83]
termui works perfectly via ssh and on my desktop terminal. But when I try to use via screen or byobu it breaks the window borders.

How can I fix the strange characters?

![captura de tela 2016-02-08 as 22 53 25](https://cloud.githubusercontent.com/assets/15484/12904455/d0c6bd66-ceb6-11e5-8a53-f11b6ce7ab96.png)

Is there any way to keep it compatible with `screen`  or `byobu` screen?

These screenshot was on `screen`. Using `byobu` is even worst because it breaks the window size.

**Comment by mranney** [comment]
My termui app works just fine in both screen and byobu. Could this be some interaction with your terminal that isn't quite right? I'm using OSX Terminal.app which sets TERM to xterm-256color. 

Can you display those unicode characters correctly in your terminal in other non-termui ways?

**Comment by jonatas** [comment]
I tried on iTerm and Ubuntu Gnome terminal. I'll verify the TERM configuration.

Thanks!

**Comment by mranney** [comment]
Any update on your issue? I'd imagine this is a somewhat common problem, so it'd be good to have the solution here for future searches.

**Comment by jonatas** [comment]
The problem is with screen. When running on local or ssh it's fine:

```
$ echo $TERM
xterm-256color```

But into screen it's "screen".
```
$ echo $TERM
screen
```

I tried to force it into screen session by exporting TERM variable with `xterm-256color` but continues with strange characters.

**Comment by jonatas** [comment]
Is there any trick on start screen or byobu for encoding or stuff like these. Because I'm starting with simple `screen -S my-session-name`.

**Comment by mranney** [comment]
I have those same TERM settings, so I don't think that's it.

Can you display those same unicode characters in your terminal in other ways? Maybe copy/paste these characters into a file and see what it looks like when you cat them.

```
const TOP_RIGHT = '┐'
const VERTICAL_LINE = '│'
const HORIZONTAL_LINE = '─'
const TOP_LEFT = '┌'
const BOTTOM_RIGHT = '┘'
const BOTTOM_LEFT = '└'
const VERTICAL_LEFT = '┤'
const VERTICAL_RIGHT = '├'
const HORIZONTAL_DOWN = '┬'
const HORIZONTAL_UP = '┴'
const QUOTA_LEFT = '«'
const QUOTA_RIGHT = '»'
```

**Comment by danieloliveira079** [comment]
Hello both,

I've tried the above approach and the result is displayed by the attached image.

Any other suggestion?

![selection_022](https://cloud.githubusercontent.com/assets/4673760/13175303/addab9fa-d6f0-11e5-9056-c6c34f9a8b4b.png)

**Comment by mranney** [comment]
Well, then at least we know it's not a termui problem. There's something about your terminal settings that doesn't want to render those characters. Is it perhaps that they don't exist in the font you are using?

**Comment by mranney** [comment]
Also, do these characters display properly outside of screen? I sort of lost track of that original context.

**Comment by jonatas** [comment]
Yes! outside it works fine! Thank you for your attention. I'll try to reconfigure those characters on a termui fork and try it!
