### ISSUE TITLE
Unable to go get due to submodule error

### ISSUE THREAD

**Issue by cwhite92** [gizak/termui#89]
When running `go get -u github.com/gizak/termui` like it says in the readme I get the following error:

```
MacBook:go chriswhite$ go get -u github.com/gizak/termui
# cd /Users/chriswhite/dev/go/src/github.com/gizak/termui; git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'vendor/github.com/mattn/go-runewidth'
package github.com/gizak/termui: exit status 1
```

Any ideas?

**Comment by gizak** [comment]
Confirmed (OS X and Linux). Somehow completely remove termui src and run _twice_ `go get github.com/gizak/termui` can update `termui`.

This may be caused by using `glide` as vendoring tool. I am looking into it.
