### ISSUE TITLE
Cannot run ttop.go example

### ISSUE THREAD

**Issue by romanvbabenko** [gizak/termui#90]
Cannot compile ttop.go just like other examples which import "extra" package

```
go run ttop.go
ttop.go:23:2: cannot find package "github.com/gizak/termui/extra" in any of:
    /usr/local/Cellar/go/1.6/libexec/src/github.com/gizak/termui/extra (from $GOROOT)
    /<$HOME>/go/src/github.com/gizak/termui/extra (from $GOPATH)
```

**Comment by gizak** [comment]
Hi @romanvbabenko , `ttop.go` is outdated but I will updated soon. Just be aware that it only works on Linux and not been widely tested.

**Comment by gizak** [comment]
Fixed https://github.com/gizak/termui/commit/7cbb70e87e46006819637b2d9327254c0ffce15c
