### ISSUE TITLE
Clear and render new grid?

### ISSUE THREAD

**Issue by DeKugelschieber** [gizak/termui#91]
How can I clear the terminal and render a new grid?
I'm trying to implement multiple views the user can switch between. The first one uses termui.Body. But when I add new rows and call render, they are appended (of course). I tried reinitializing the Body

```
termui.Body = termui.NewGrid(...)
```

and creating a separate grid:

```
grid := termui.newGrid(...)
grid.Align()
termui.Render(grid)
```

But both result in an empty terminal.

**Comment by anujkhare** [comment]
You could reinitialize the slice `termui.Body.Rows` by using:

`termui.Body.Rows = []*termui.Body.Rows{}` 

I am new to Go, so not sure if this is the best way to do this.

**Comment by miguelmota** [comment]
To reset, before `AddRows` I did:

```go
ui.Body.Rows = ui.Body.Rows[:0]
```
