### ISSUE TITLE
UseTheme(string) undefined

### ISSUE THREAD

**Issue by hyleung** [gizak/termui#97]
In the examples (e.g. https://github.com/gizak/termui/blob/master/_example/theme.go), there's a `UseTheme(string)` function being used, that as far as I can tell is undefined. I couldn't find any mention of it in the issues or PRs for this repo. I _think_ it's been removed (https://github.com/gizak/termui/blob/master/theme.go#L82-L90)?

If so, maybe a good idea to update the example code (I'd be happy to help out with a PR if necessary).

**Comment by mehrdadrad** [comment]
any update on this?

**Comment by hyleung** [comment]
@mehrdadrad ¯\\_(ツ)_/¯ 

To be clear, this isn't necessarily a blocker - you can still achieve the same end result by poking stuff into `ui.ColorMap`. I was really just pointing out that the docs were a bit confusing (or, being a complete Go newbie, I was completely missing something).
